---
apiVersion: v1
kind: Service
metadata:
  name: microcoffee-web
  labels:
    app: microcoffee
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 8080
      name: web-http
    - port: 9443
      targetPort: 8443
      name: web-https
  selector:
    app: microcoffee
    tier: frontend
  externalIPs:
    - 192.168.99.100
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microcoffee-web
  labels:
    app: microcoffee
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microcoffee
        tier: frontend
    spec:
      containers:
        - name: web
          image: microcoffeeoncloud-web:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
              name: web-http
            - containerPort: 8443
              name: web-https
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "devdocker"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://192.168.99.100:8091"
