---
apiVersion: v1
kind: Service
metadata:
  name: microcoffee-creditrating
  labels:
    app: microcoffee
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      name: credit-http
    - port: 8446
      targetPort: 8446
      name: credit-https
  selector:
    app: microcoffee
    tier: backend
  externalIPs:
    - 192.168.99.100
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: microcoffee-creditrating
  labels:
    app: microcoffee
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microcoffee
        tier: backend
    spec:
      containers:
        - name: creditrating
          image: microcoffeeoncloud-creditrating:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8083
              name: credit-http
            - containerPort: 8446
              name: credit-https
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "devdocker"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://192.168.99.100:8091"
              